source 'https://github.com/CocoaPods/Specs'
use_frameworks!

platform :ios, '9.0'

target 'Iris_Example' do
  pod 'Iris', :path => '../'
  pod 'Iris/Logging', :path => '../'
  pod 'Iris/Alamofire', :path => '../'

  target 'Iris_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
