source 'https://github.com/CocoaPods/Specs'
use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'Iris_Example' do
  pod 'Iris-iOS', :path => '../'
  pod 'Iris-iOS/Defaults', :path => '../'

  pod 'SwiftLint'

  target 'Iris_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
